# Generated by Django 2.2.5 on 2020-02-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img/img.jpg', upload_to='')),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'market',
            },
        ),
    ]
