# Generated by Django 3.0.4 on 2020-03-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_market_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='creator',
        ),
    ]
