# Generated by Django 3.0.4 on 2020-05-09 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_messageus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageus',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 12, 49, 41, 993468), verbose_name='date sent'),
        ),
    ]
